# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ce884c6e0792f6946883c8d1ee9c0ba4076ddd3234f91cd56dce8c5daf72062080dbf761e99b9b93ed349bccb82e756ed3dfda4b37d29216952f27a55a25083

test:
  secret_key_base: 8a14d1550e1ae215b61fa05d1ceb9ba3b3193155db7398eadaeff7c565e0a2965482f2836f12d40db56e7cb3f76db198882169ac86d80b4193590923ae4e2fe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
